version: '3'
services:
  db:
    image: ploh/mysqlrtb
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rtb4free
      - MYSQL_DATABASE=rtb4free
      - MYSQL_USER=ben
      - MYSQL_PASSWORD=test
  web:
    image: ploh/rtbadmin_open
    command: cron && bash -c "./wait-for-it.sh db:3306 --timeout=120; bundle exec rails s -p 3000 -b '0.0.0.0' "
    ports:
      - "3000:3000"
    environment:
      - RTB4FREE_CUSTOMER_NAME=RTB4FREE
      - RTB4FREE_DATABASE_HOST=db
      - RTB4FREE_DATABASE_PORT=3306
      - RTB4FREE_DATABASE_USERNAME=ben
      - RTB4FREE_DATABASE_PASSWORD=test
      - RTB4FREE_DATABASE_NAME=rtb4free
      - RTB4FREE_ELASTICSEARCH_REPORTS_ENABLE=false
      - RTB4FREE_ELASTICSEARCH_HOST=
      - RTB4FREE_ELASTICSEARCH_KIBANA_HOST=
      - RTB4FREE_ELASTICSEARCH_KIBANA_PORT=
      - RTB4FREE_ELASTICSEARCH_KIBANA_URL=
      - RTB4FREE_ELASTICSEARCH_REQUESTS_INDEX=bidderlogs
      - RTB4FREE_ELASTICSEARCH_STATS_INDEX=stats
